### ISSUE TITLE
Zduplikowany plik wynikowy testu

### ISSUE THREAD

**Issue by kubak95** [IIS-ZPI/ZPI2020_zaoczni_Grupa_1#107]
Streszczenie:
Po uruchomieniu testu tworzą się 2 pliki zamiast 1

Kroki do reprodukcji:
1. Przejść do katalogu głównego aplikacji
2. Uruchomić testy komendą `python -m pytest  test/performancetest/test_DataParser.py`

Oczekiwane rezultaty:
Po uruchomieniu testu tworzy się plik z wynikami w podkatalogu test/performancetest/results

Rzeczywiste rezultaty:
Po uruchomieniu testu tworzy się plik z wynikami w podkatalogu test/performancetest/result oraz pusty plik w katalogu z którego uruchamia się testy

**Comment by arszonto** [comment]
Problem został zreprodukowany w moim środowisku pracy. Bug jest zaakceptowany i przeniesiony do backlogu zespołu 'Grupa 1'.

**Comment by kubak95** [comment]
Przetestowano rozwiązanie. Wykonałem kroki do reprodukcji. Rezultaty uzyskane są zgodne z oczekiwanymi - w hierarchii katalogów zduplikowany plik nie występuje
![image](https://user-images.githubusercontent.com/29385596/107157556-f4e24080-6984-11eb-94ad-d45ba6865aad.png)
