### ISSUE TITLE
Testy Manualne: Interfejs użytkownika

### ISSUE THREAD

**Issue by arszonto** [IIS-ZPI/ZPI2020_zaoczni_Grupa_1#51]

**Comment by kubak95** [comment]
Podczas testów manualnych dokonałem weryfikacji działania aplikacji oraz tzw "Monkey Test", polegający na próbie doprowadzenia aplikacji do stanu nieużywalności. Błąd został zgłoszony zespołowi developerskiemu @arszonto  @ablesable
